fix: QA of newly added docstrings.
flojoy-ai/nodes pull request #266
Opened 2023-08-30 05:25 UTC by shani-leroux

### Description

- [ ] I've included a concise description of what each node does

### Styleguide

- [ ] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [ ] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

### Testing

- [ ] This PR includes a unit test ([example here](https://github.com/flojoy-io/nodes/blob/c28808f2d0aec8f116cdb3fccb46c4f5256574e9/TRANSFORMERS/ARITHMETIC/ADD/ADD_test_.py) and/or ideally a screenshot of the node's output on an example app.

2023-08-30 17:08 UTC, JeffDotPng reviewed
Looks pretty good, nice work, just a few small changes needed
I don't have the background to review the changes to the docstring for `EXTREMA_DETERMINATION` so I will let @trbritt or @dstrande look at it.

2023-08-30 17:08 UTC, JeffDotPng commented on LOADERS/LOCAL_FILE_SYSTEM/BATCH_PROCESSOR/BATCH_PROCESSOR.py
> +    retval : TextBlob
The name of this output should be `fname`, and there should be another return value here which is `n_files`

2023-08-30 17:08 UTC, JeffDotPng commented on LOGIC_GATES/LOOP_TOOLS/BREAK/BREAK.py
> +    default : Optional [DataContainer]
The type here should simply be `DataContainer`

2023-08-30 17:08 UTC, JeffDotPng commented on TRANSFORMERS/IMAGE_PROCESSING/REGION_PROPERTIES/REGION_PROPERTIES.py
> +    default : Optional [Image | Grayscale]
Type here should be Image | Grayscale

2023-08-30 17:08 UTC, JeffDotPng commented on TRANSFORMERS/IMAGE_PROCESSING/EXTREMA_DETERMINATION/EXTREMA_DETERMINATION.py
> +    image_mask : Optional [Grayscale | Matrix], None
Grayscale | Matrix

2023-08-31 16:19 UTC, dstrande commented
Might wait for @trbritt to see what he thinks. @JeffDotPng @itsjoeoui do you have an opinion on how complicated a docstring can be? 

Personally I think if a node has a complex use-case then it's fine if the docstring is very in depth.

2023-08-31 16:26 UTC, trbritt commented
There were many reasons why I've kept these docstrings as in-depth as I did. 

The techniques they implement are complex and use latest research, and the first algorithm in the `EXTREMA_DETERMINATION` node was jointly developed by myself and a collaborator, which is why I give them credit in the doc string of that node. IMHO,  nodes that implement complicated algorithms should be allowed to keep a references section with an in-depth doc string, so that interested users have all the tools available to them to understand the functionality of the node.

All the changes look fine with the caveat of reincluding the References sections of the docstrings.

2023-08-31 16:32 UTC, JeffDotPng commented
> There were many reasons why I've kept these docstrings as in-depth as I did.
> 
> The techniques they implement are complex and use latest research, and the first algorithm in the `EXTREMA_DETERMINATION` node was jointly developed by myself and a collaborator, which is why I give them credit in the doc string of that node. IMHO, nodes that implement complicated algorithms should be allowed to keep a references section with an in-depth doc string, so that interested users have all the tools available to them to understand the functionality of the node.
> 
> All the changes look fine with the caveat of reincluding the References sections of the docstrings.

I agree, plus users won't see this information unless they go on the docs or view the python source code in `studio` (no walls of text in the parameter descriptions) so it's not disruptive to UX.
The references section should definitely be reincluded!

2023-09-01 18:02 UTC, JeffDotPng requested changes
Noticed a few more things

2023-09-01 18:02 UTC, JeffDotPng commented on TRANSFORMERS/IMAGE_PROCESSING/REGION_PROPERTIES/REGION_PROPERTIES.py
> +    while the second is provided by the regionprops function of the 'scikit-image'.
The text from before is more accurate:
```
    The first step is provided by the morphology library of scikit-image's label function,
    while the second is provided by scikit-image's regionprops function.
```

2023-09-01 18:02 UTC, JeffDotPng commented on TRANSFORMERS/IMAGE_PROCESSING/REGION_PROPERTIES/REGION_PROPERTIES.py
>          features as determined by this node.
```suggestion
        A Plotly figure containing the illustrated features as determined by this node.
```

2023-09-01 19:19 UTC, trbritt commented
All of @JeffDotPng's proposed changes I approve for the record

2023-09-05 14:40 UTC, JeffDotPng approved these changes
lgtm

2023-09-05 14:43 UTC, merged